name: mpy build
on: push
env:
  SRC_FILE: thimble.py
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Linting...
        run: |
          pip3 install ruff
          python3 -m ruff check $SRC_FILE
      - name: Compiling bytecode...
        run: |
          pip3 install mpy-cross
          python3 -m mpy_cross $SRC_FILE
      - name: Creating class doc...
        run: |
          pip3 install pdoc3
          pdoc3 --force --html --output-dir=docs $SRC_FILE
      - name: Committing changes...
        run: |
          if [ $(git diff | wc -l) -gt 0 ]; then
            git config --global user.name "$GITHUB_REPOSITORY_OWNER"
            git config --global user.email "$GITHUB_REPOSITORY_OWNER@users.noreply.github.com"
            git commit -am "GitHub Actions"
            git push
          fi
